ALTER TABLE public.business_terminology
  ADD COLUMN IF NOT EXISTS context text DEFAULT 'all',
  ADD COLUMN IF NOT EXISTS disambiguation text;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS optimization_notes text;

INSERT INTO public.business_terminology (term, type, replacement, category, context, disambiguation, is_global)
VALUES
-- EXAUSTÃO
('Campana','avoid','Hotte de Cozinha','Exaustão','title',null,true),
('Coifa','synonym','Hotte','Exaustão','tags',null,true),
('Hotte Industrial Inox','preferred',null,'Exaustão','title',null,true),
('Hotte de Cozinha','preferred',null,'Exaustão','description',null,true),
('Campânula de Exaustão','synonym',null,'Exaustão','description',null,true),
('Sistema de Extração','synonym',null,'Exaustão','description',null,true),
('Exaustor Industrial','synonym',null,'Exaustão','tags',null,true),
('Apanha-fumos','synonym',null,'Exaustão','tags',null,true),
('Exhaust Hood','synonym',null,'Exaustão','tags',null,true),
-- COZEDURA — Fogões
('Cocina','avoid','Fogão Industrial','Cozedura','title',null,true),
('Fogão Industrial','preferred',null,'Cozedura','title',null,true),
('Fogão a Gás Profissional','preferred',null,'Cozedura','description',null,true),
('Fogão Elétrico Profissional','preferred',null,'Cozedura','description',null,true),
('Equipamento de Confeção','synonym',null,'Cozedura','description',null,true),
('Linha de Confeção','preferred',null,'Cozedura','description',null,true),
('Cooking Range','synonym',null,'Cozedura','tags',null,true),
('Tacho','synonym',null,'Cozedura','description',null,true),
('Frigideira','synonym',null,'Cozedura','description',null,true),
('Marmita Industrial','synonym',null,'Cozedura','description',null,true),
-- COZEDURA — Fornos
('Horno','avoid','Forno Industrial','Cozedura','title',null,true),
('Forno Industrial','preferred',null,'Cozedura','title',null,true),
('Forno de Convecção','preferred',null,'Cozedura','description',null,true),
('Forno Combinado','preferred',null,'Cozedura','description',null,true),
('Combi Oven','synonym',null,'Cozedura','tags',null,true),
-- COZEDURA — Fritadeiras
('Freidora','avoid','Fritadeira Industrial','Cozedura','title',null,true),
('Fritadeira Industrial','preferred',null,'Cozedura','title',null,true),
('Fritadeira Elétrica','preferred',null,'Cozedura','description',null,true),
('Fritadeira a Gás','preferred',null,'Cozedura','description',null,true),
('Equipamento de Fritura','synonym',null,'Cozedura','description',null,true),
('Deep Fryer','synonym',null,'Cozedura','tags',null,true),
-- COZEDURA — Grelhadores
('Parrilla','avoid','Grelhador Industrial','Cozedura','title',null,true),
('Plancha','avoid','Chapa de Grelhar','Cozedura','title',null,true),
('Grelhador Industrial','preferred',null,'Cozedura','title',null,true),
('Chapa de Grelhar','preferred',null,'Cozedura','title',null,true),
('Grelhador a Gás','synonym',null,'Cozedura','description',null,true),
('Chapa Lisa','synonym',null,'Cozedura','description',null,true),
('Chapa Mista','synonym',null,'Cozedura','description',null,true),
('Griddle','synonym',null,'Cozedura','tags',null,true),
-- FRIO
('Nevera','avoid','Frigorífico Profissional','Frio','title',null,true),
('Refrigerador','avoid','Frigorífico Profissional','Frio','title',null,true),
('Frigorífico Profissional','preferred',null,'Frio','title',null,true),
('Armário Refrigerado','synonym',null,'Frio','description',null,true),
('Câmara Frigorífica','preferred',null,'Frio','description',null,true),
('Frigorífico Inox','synonym',null,'Frio','description',null,true),
('Cold Cabinet','synonym',null,'Frio','tags',null,true),
('Congelador Industrial','preferred',null,'Frio','title',null,true),
('Arca Congeladora','synonym',null,'Frio','description',null,true),
('Arcão Congelador','synonym',null,'Frio','description',null,true),
('Câmara de Congelação','synonym',null,'Frio','description',null,true),
('Armário de Congelação','synonym',null,'Frio','description',null,true),
('Abatedor de Temperatura','preferred',null,'Frio','title',null,true),
('Célula de Arrefecimento Rápido','synonym',null,'Frio','description',null,true),
('Blast Chiller','synonym',null,'Frio','tags',null,true),
-- LAVAGEM — Máquinas
('Lavavajillas','avoid','Máquina de Lavar Loiça Industrial','Lavagem','title','Usar APENAS quando o produto é uma MÁQUINA com ciclos automáticos, porta frontal ou capot. NUNCA para bancadas com cuba/pia.',true),
('Máquina de Lavar Loiça Industrial','preferred',null,'Lavagem','title','Apenas para máquinas automáticas de lavagem. Nunca para bancadas ou cubas inox.',true),
('Máquina de Lavar Louça','synonym',null,'Lavagem','description',null,true),
('Lava-Louça Industrial','synonym',null,'Lavagem','description',null,true),
('Máquina de Lavagem Profissional','synonym',null,'Lavagem','description',null,true),
('Dishwasher','synonym',null,'Lavagem','tags',null,true),
-- LAVAGEM — Bancadas/Cubas
('Fregadero','avoid','CONTEXT_DEPENDENT','Lavagem','title','REGRA: Se produto tem dimensões >800mm ou pernas/estrutura → "Bancada com Cuba Inox" ou "Lavadouro Inox". Se cuba solta pequena → "Cuba de Encastrar". NUNCA traduzir como "Máquina de Lavar Loiça".',true),
('Bancada com Cuba Inox','preferred',null,'Lavagem','title','Para fregaderos com pernas/estrutura. Produto tipo mobiliário com pia integrada.',true),
('Lavadouro Inox','preferred',null,'Lavagem','title','Para produtos primariamente de lavagem sem grande zona de trabalho.',true),
('Cuba de Encastrar','synonym',null,'Lavagem','description','Apenas para cubas soltas sem estrutura/pernas.',true),
('Bancada de Lavagem','synonym',null,'Lavagem','description',null,true),
('Pia Industrial','synonym',null,'Lavagem','tags',null,true),
('Lava-Mãos Profissional','preferred',null,'Lavagem','title','APENAS para lavatórios pequenos de mãos. Não para cubas de louça.',true),
-- SELF-SERVICE / BUFFET
('Vitrina Caliente','avoid','Vitrine de Quentes','Self-Service','title',null,true),
('Vitrine de Quentes','preferred',null,'Self-Service','title',null,true),
('Expositor de Quentes','preferred',null,'Self-Service','title',null,true),
('Estufa','synonym',null,'Self-Service','description',null,true),
('Vitrine Aquecida','synonym',null,'Self-Service','description',null,true),
('Balcão de Quentes','synonym',null,'Self-Service','description',null,true),
('Estufa de Buffet','synonym',null,'Self-Service','tags',null,true),
('Banho-Maria','preferred',null,'Self-Service','title',null,true),
('Bain Marie','synonym',null,'Self-Service','tags',null,true),
('Cuba de Banho-Maria','synonym',null,'Self-Service','description',null,true),
('Marmita','synonym',null,'Self-Service','description',null,true),
('Expositor Refrigerado','preferred',null,'Self-Service','title',null,true),
('Vitrine de Frio','synonym',null,'Self-Service','description',null,true),
('Conservador de Frios','synonym',null,'Self-Service','description',null,true),
('Linha de Buffet','synonym',null,'Self-Service','description',null,true),
('Serviço de Buffet','synonym',null,'Self-Service','description',null,true),
('Vitrine de Pastelaria','preferred',null,'Self-Service','title','Usar quando produto menciona bolos, doces, pastelaria ou prateleiras internas múltiplas.',true),
('Vitrine de Charcutaria','preferred',null,'Self-Service','title','Usar quando produto menciona fiambre, queijo, enchidos, ou temperatura 0-5°C.',true),
('Vitrina','avoid','CONTEXT_DEPENDENT','Self-Service','title','REGRA: Ler descrição completa. Se menciona pastelaria/bolos → "Vitrine de Pastelaria". Se charcutaria/frios/queijos → "Vitrine de Charcutaria". Se ambíguo → usar "Vitrine Refrigerada" e preencher optimization_notes.',true),
-- MOBILIÁRIO INOX
('Bancada Inox','preferred',null,'Mobiliário','title',null,true),
('Mesa de Trabalho Inox','synonym',null,'Mobiliário','description',null,true),
('Bancada de Cozinha Profissional','synonym',null,'Mobiliário','description',null,true),
('Estante Inox','preferred',null,'Mobiliário','title',null,true),
('Prateleira Inox','synonym',null,'Mobiliário','description',null,true),
('Prateleira de Cozinha','synonym',null,'Mobiliário','description',null,true),
('Armário Inox','preferred',null,'Mobiliário','title',null,true),
('Base Neutra','preferred',null,'Mobiliário','title','Estrutura de suporte sem função térmica. Para bases sob equipamentos de confeção.',true),
('Suporte de Equipamento','synonym',null,'Mobiliário','description',null,true),
('Carro de Transporte','preferred',null,'Mobiliário','title',null,true),
('Escorredor Inox','preferred',null,'Mobiliário','title',null,true),
('Stainless Steel Worktable','synonym',null,'Mobiliário','tags',null,true),
-- PREPARAÇÃO
('Máquina de Gelo','preferred',null,'Preparação','title',null,true),
('Fabricador de Gelo','synonym',null,'Preparação','description',null,true),
('Produtor de Gelo','synonym',null,'Preparação','tags',null,true),
('Ice Maker','synonym',null,'Preparação','tags',null,true),
('Fiambreira Industrial','preferred',null,'Preparação','title','Em PT-PT nunca usar "Cortador de Frios" (brasileirismo).',true),
('Cortadora','avoid','Fiambreira Industrial','Preparação','title',null,true),
('Cortador de Frios','avoid','Fiambreira Industrial','Preparação','title','Brasileirismo. Em PT-PT usar Fiambreira.',true),
('Fatiador','synonym',null,'Preparação','description',null,true),
('Slicer','synonym',null,'Preparação','tags',null,true),
('Amassadeira','preferred',null,'Preparação','title',null,true),
('Batedeira Industrial','preferred',null,'Preparação','title',null,true),
('Laminador de Massa','preferred',null,'Preparação','title',null,true),
-- AQUECIMENTO
('Salamandra','preferred',null,'Aquecimento','title',null,true),
('Gratinador','synonym',null,'Aquecimento','description',null,true),
('Estufa de Aquecimento','preferred',null,'Aquecimento','title',null,true),
('Rechaud','synonym',null,'Aquecimento','description',null,true),
('Aquecedor de Pratos','preferred',null,'Aquecimento','title',null,true),
('Armário Quente','synonym',null,'Aquecimento','description',null,true),
-- CAFÉ
('Máquina de Café Profissional','preferred',null,'Café','title',null,true),
('Grupo Espresso','synonym',null,'Café','description',null,true),
('Moinho de Café','preferred',null,'Café','title',null,true),
('Coffee Grinder','synonym',null,'Café','tags',null,true),
-- PALAMENTA / UTENSÍLIOS
('Cubertería','avoid','Talheres Profissionais','Palamenta','title',null,true),
('Talheres Profissionais','preferred',null,'Palamenta','title',null,true),
('Utensílios de Cozinha','preferred',null,'Palamenta','title',null,true),
('Panela Industrial','preferred',null,'Palamenta','title',null,true),
('Frigideira Profissional','preferred',null,'Palamenta','title',null,true),
('Caçarola','synonym',null,'Palamenta','description',null,true),
('Tacho Industrial','synonym',null,'Palamenta','description',null,true),
('GN Container','synonym',null,'Palamenta','tags',null,true),
('Cuba Gastronorm','preferred',null,'Palamenta','title','Para recipientes GN padronizados. Não confundir com cubas de lavagem.',true),
('Bandeja Gastronómica','synonym',null,'Palamenta','description',null,true),
('Gastronorm Pan','synonym',null,'Palamenta','tags',null,true),
-- LAVANDARIA
('Lavadora Industrial','preferred',null,'Lavandaria','title',null,true),
('Máquina de Lavar Roupa Industrial','synonym',null,'Lavandaria','description',null,true),
('Secador Industrial','preferred',null,'Lavandaria','title',null,true),
('Calandra','preferred',null,'Lavandaria','title','Máquina de passar/engomar roupa em rolo. Não confundir com calandras de papel.',true),
('Ferro de Engomar Industrial','preferred',null,'Lavandaria','title',null,true),
('Mesa de Engomar Profissional','synonym',null,'Lavandaria','description',null,true),
('Laundry Equipment','synonym',null,'Lavandaria','tags',null,true),
-- LIMPEZA / HIGIENE
('Dispensador de Sabão','preferred',null,'Limpeza','title',null,true),
('Doseador de Detergente','synonym',null,'Limpeza','description',null,true),
('Carro de Limpeza','preferred',null,'Limpeza','title',null,true),
('Esfregona Industrial','preferred',null,'Limpeza','title',null,true),
('Mopa Profissional','synonym',null,'Limpeza','description',null,true),
('Aspirador Industrial','preferred',null,'Limpeza','title',null,true),
('Contentor de Resíduos','preferred',null,'Limpeza','title',null,true),
('Caixote do Lixo Profissional','synonym',null,'Limpeza','description',null,true),
('Waste Bin','synonym',null,'Limpeza','tags',null,true),
-- PASTELARIA
('Expositor de Pastelaria','synonym',null,'Pastelaria','description',null,true),
('Armário de Fermentação','preferred',null,'Pastelaria','title',null,true),
('Câmara de Fermentação','synonym',null,'Pastelaria','description',null,true),
('Forno de Pastelaria','preferred',null,'Pastelaria','title',null,true),
('Batedeira Planetária','preferred',null,'Pastelaria','title',null,true),
('Misturadora Industrial','synonym',null,'Pastelaria','description',null,true),
('Laminador','preferred',null,'Pastelaria','title','Máquina de laminar massa. Não confundir com laminador de documentos.',true),
('Temperadora de Chocolate','preferred',null,'Pastelaria','title',null,true)
ON CONFLICT DO NOTHING;